### ISSUE TITLE
Publicar código libro

### ISSUE THREAD

**Issue by stivenbr** [rdiazconcha/libro-xamarin.forms-en-accion#1]
**¡¡Hola Rodrigo!!**

Muchas gracias por compartir conocimientos en el libro **"XAMARIN.FORMS en acción - Aplicaciones de negocio"** es muy útil y más cuando está iniciando en este mundo de la programación de las aplicaciones hibridas.

Me gustaría que publicaras el código que este impreso en el libro, de esta manera me quedaría fácil de entender y orientarme de la forma adecuada.

Muchas Gracias.

**Comment by rdiazconcha** [comment]
¡Hola! Justamente éste es el repositorio del código del libro.  Cada rama (branch) corresponde a un capítulo del libro.

¡Gracias y saludos!
